{% set name = "pyramid_session_redis" %}
{% set version = "1.6.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pyramid_session_redis-{{ version }}.tar.gz
  sha256: bbe74e27eb199cc565d45163d970a358a7084d41f46847f782fbdd1d84b9c8e9

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - redis-py >=2.10
    - pyramid >=2
    - six

test:
  imports:
    - pyramid_session_redis
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/jvanasco/pyramid_session_redis
  summary: High performance and actively maintained server-side session framework for Pyramid and Redis.
  license: CC0-1.0
  license_file: LICENSE.txt

about:
  home: https://pypi.org/project/{{ name }}/
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: 'Server-Side Sessions plugin for the Pyramid web framework.'
  description: |
      pyramid_session_redis is a mature, stable and actively maintained Server-Side
      Sessions plugin for the Pyramid web framework.

      Originally, this library was a fork of pyramid_redis_sessions,
      focused on improvements and API changes designed for high performance
      (particularly with servers under load), and a slightly different API
      designed for developer convenience.
  dev_url: https://github.com/ericrasmussen/pyramid_redis_sessions
  doc_url: https://github.com/ericrasmussen/pyramid_redis_sessions

extra:
  recipe-maintainers:
    - ChrisBarker-NOAA
    - JamesMakela-NOAA
